### PR TITLE
An Introduction to JavaScript

### PR DESCRIPTION
**Pull request by danipoma**
Hello.

Creating a PR for first translated page into Czech.
If I am doing something wrong, please say so as this is my first time using git.

Best Regards.

### CODE REVIEW

**Comment by iliakan** [comment]
Please ask the maintainer, is he alive? :) If he isn't then tell me.

**Comment by otmon76** [comment]
Hello,
I am alive. I am sorry but I thought that other users must ask me before starting translation. I will talk with danipoma.

**Comment by iliakan** [comment]
@otmon76 great to hear from you.

Anyone is free to contribute, unless someone else took the article for the translation.

As the maintainer, I assume you have enough JS knowledge to review the translations? 

I hope to see the Czech translation going ahead =)

**Comment by danipoma** [comment]
@otmon76 How exactly are we going to talk this through? Once again I am sorry for my missing knowledge about git and getting info about it. I have deleted this pull request, because at first I thought that this project didn't start just yet, but then I found that there actually is a list of articles for taking and this one was already in progress on your side. 

What is the workflow? Can I help you with translation? How can I reserve that article in issue list? Is there any standard on which you should create PR like should I create PR to javascript-tutorial repo when I have more articles translated on my repo or should I create PR per each document?

Thank you for information.

**Comment by otmon76** [comment]
I am sorry. I don't know Github too much yet and I didn't notice that I must commit my pull requests here, not to my branch. Each article must be reviewed by 2 users before publishing. I have translated first 2 chapters but I need reviewers and nobody was interested yet, so I didn't commit them yet.

Also I would like to ask you: would you want to take the administration from me? If you are interested please contact me at onderek@volny.cz.

**Comment by danipoma** [comment]
Nothing to be sorry about, I just skimmed few articles today to be able to push changes. You can push changes to remote repo of your clone and then promote them to origin repo you cloned, for more info look on some article.

Regarding that administration thing. I don't know how much active I will be as well, but I could try it.
I will contact you on your e-mail as well.

Best Regards.

**Comment by iliakan** [comment]
@otmon76 if @danipoma translation is good, I can add him to maintainers.

Also, 2 reviewers per article is a recommendation, not a strict rule.

**Comment by danipoma** [comment]
Hello @iliakan 
@otmon76 and I discussed through e-mail correspondence that it would be for the best if you would promote me to maintainer status as well, it would be for the best @otmon76 if you would confirm my statement.

Regarding that 2 reviewers rule is probably not going to fare well at least for now, because only I and @otmon76 is somewhat interested in translating this guide,

Regardless of our current translation status, I also wanted to say that I really appreciate this guide, because of its structure and how topics are presented and overall just how digestible that content is. I firmly believe that if we want to have more developers, we need to make tools like this to support them in their learning curve. I believe that things like javascript.info, caniuse.com, codesandbox.io, devdocs.io, MDN, regex101.com, freecodecamp etc. are all things that play a major role in developer's development.

**Comment by iliakan** [comment]
Done!

**Pull request closed without merging**
